apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc-project
  template:
    metadata:
      labels:
        app: doc-project
    spec:
      containers:
        - name: doc-project
          image: balumidikondla/doc_project:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: doc-project-service
spec:
  selector:
    app: doc-project
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
