apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc-project
  template:
    metadata:
      labels:
        app: doc-project
    spec:
      containers:
        - name: doc-project
          image: balumidikondla/doc_project:9
          ports:
            - containerPort: 8080


